#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Aug 02, 2022 05:01:45 PM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import santomiele_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("409x447+505+150")
        top.minsize(120, 1)
        top.maxsize(3604, 1072)
        top.resizable(1,  1)
        top.title("Santomiele")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Labelframe1 = tk.LabelFrame(self.top)
        self.Labelframe1.place(relx=0.049, rely=0.034, relheight=0.931
                , relwidth=0.902)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Set/Get Log''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")

        self.Entry1 = tk.Entry(self.Labelframe1)
        self.Entry1.place(relx=0.081, rely=0.144, height=40, relwidth=0.824
                , bordermode='ignore')
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Courier New} -size 14")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")
        #self.Entry1.configure(text='''192.168.10.101''')
        self.Entry1.insert(END, '192.168.1.142')

        self.Label1 = tk.Label(self.Labelframe1)
        self.Label1.place(relx=0.081, rely=0.072, height=21, width=164
                , bordermode='ignore')
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Greenhouse IP''')


##NUOVA
        self.Button0 = tk.Button(self.Labelframe1)
        self.Button0.place(relx=0.542, rely=0.305, height=34, width=137
                , bordermode='ignore')
        self.Button0.configure(activebackground="#ececec")
        self.Button0.configure(activeforeground="#000000")
        self.Button0.configure(background="#d9d9d9")
        self.Button0.configure(command=santomiele_support.ReadLog)
        self.Button0.configure(compound='left')
        self.Button0.configure(disabledforeground="#a3a3a3")
        self.Button0.configure(foreground="#000000")
        self.Button0.configure(highlightbackground="#d9d9d9")
        self.Button0.configure(highlightcolor="black")
        self.Button0.configure(pady="0")
        self.Button0.configure(text='''Greenhouse''')


        self.Entry0 = tk.Entry(self.Labelframe1)
        self.Entry0.place(relx=0.081, rely=0.305, height=34, width=137
                , bordermode='ignore')
        self.Entry0.configure(background="white")
        self.Entry0.configure(disabledforeground="#a3a3a3")
        self.Entry0.configure(font="-family {Courier New} -size 8")
        self.Entry0.configure(foreground="#000000")
        self.Entry0.configure(highlightbackground="#d9d9d9")
        self.Entry0.configure(highlightcolor="black")
        self.Entry0.configure(insertbackground="black")
        self.Entry0.configure(selectbackground="blue")
        self.Entry0.configure(selectforeground="white")
        self.Entry0.configure(state= "disabled")
##

        self.Button1 = tk.Button(self.Labelframe1)
        self.Button1.place(relx=0.542, rely=0.505, height=74, width=137
                , bordermode='ignore')
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=santomiele_support.SetTemp)
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Set Temperature''')

        self.Button2 = tk.Button(self.Labelframe1)
        self.Button2.place(relx=0.542, rely=0.745, height=74, width=137
                , bordermode='ignore')
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=santomiele_support.GetDatas)
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Get Log''')

        self.Entry2 = tk.Entry(self.Labelframe1)
        self.Entry2.place(relx=0.108, rely=0.529, height=50, relwidth=0.309
                , bordermode='ignore')
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="-family {Courier New} -size 30")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="blue")
        self.Entry2.configure(selectforeground="white")
        self.Entry2.insert(END, '40')

        self.Label2 = tk.Label(self.Labelframe1)
        self.Label2.place(relx=0.088, rely=0.457, height=21, width=150
                , bordermode='ignore')
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Temperature [°C] [31-49]''')

def start_up():
    santomiele_support.main()

if __name__ == '__main__':
    santomiele_support.main()


